config/routes.rb
Listaslistas::Application.routes.draw do
  get 'admin' => 'admin#index'
controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end
  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :usuarios

  resources :homes

  resources :zonas

  resources :salas

  resources :reservas

  resources :imagen_eventos

  resources :imagen_discos

  resources :imagens

  resources :eventos

  resources :discotecas

  resources :ciudads

end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
end

app/models/discoteca.rb
class Discoteca < ActiveRecord::Base
validates :nombre, :cod_ciudad, :presence => true
end

app/models/evento.rb
class Evento < ActiveRecord::Base
validates :cod_disco, :nombre, :fecha ,:hora, :presence => true

validates :logo_web, :format => {
:with => %r{\.(gif|jpg|png)$}i,
:message => 'must be a URL for GIF, JPG or PNG image.'
}
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/imagen.rb
class Imagen < ActiveRecord::Base
end

app/models/imagen_disco.rb
class ImagenDisco < ActiveRecord::Base
end

app/models/imagen_evento.rb
class ImagenEvento < ActiveRecord::Base
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
end

app/models/sala.rb
class Sala < ActiveRecord::Base
end

app/models/usuario.rb
require 'digest/sha2'

class Usuario < ActiveRecord::Base
validates :nombre, :presence => true, :uniqueness => true

validates :password, :confirmation => true
attr_accessor :password_confirmation
attr_reader :password

validate :password_must_be_present

class << self
	def authenticate(nombre, password)
			if usuario = find_by_nombre(nombre)
				if usuario.hashed_password == encrypt_password(password, usuario.salt)
				usuario
			end
		end
	end
	def encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end
end

def password=(password)
@password = password
	if password.present?
		generate_salt
		self.hashed_password = self.class.encrypt_password(password, salt)
	end
end

after_destroy :ensure_an_admin_remains

def ensure_an_admin_remains
	if User.count.zero?
		raise "Can't delete last user"
	end
end

private
	def password_must_be_present
		errors.add(:password, "Missing password") unless hashed_password.present?
	end

	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s
	end
end

app/models/zona.rb
class Zona < ActiveRecord::Base
end

app/controllers/ciudads_controller.rb
class CiudadsController < ApplicationController
  # GET /ciudads
  # GET /ciudads.json
  def index
    @ciudads = Ciudad.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ciudads }
    end
  end

  # GET /ciudads/1
  # GET /ciudads/1.json
  def show
    @ciudad = Ciudad.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ciudad }
    end
  end

  # GET /ciudads/new
  # GET /ciudads/new.json
  def new
    @ciudad = Ciudad.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ciudad }
    end
  end

  # GET /ciudads/1/edit
  def edit
    @ciudad = Ciudad.find(params[:id])
  end

  # POST /ciudads
  # POST /ciudads.json
  def create
    @ciudad = Ciudad.new(params[:ciudad])

    respond_to do |format|
      if @ciudad.save
        format.html { redirect_to @ciudad, notice: 'Ciudad was successfully created.' }
        format.json { render json: @ciudad, status: :created, location: @ciudad }
      else
        format.html { render action: "new" }
        format.json { render json: @ciudad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ciudads/1
  # PUT /ciudads/1.json
  def update
    @ciudad = Ciudad.find(params[:id])

    respond_to do |format|
      if @ciudad.update_attributes(params[:ciudad])
        format.html { redirect_to @ciudad, notice: 'Ciudad was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @ciudad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ciudads/1
  # DELETE /ciudads/1.json
  def destroy
    @ciudad = Ciudad.find(params[:id])
    @ciudad.destroy

    respond_to do |format|
      format.html { redirect_to ciudads_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/ciudads_helper.rb
module CiudadsHelper
end

app/helpers/discotecas_helper.rb
module DiscotecasHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/imagens_helper.rb
module ImagensHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/zonas_helper.rb
module ZonasHelper
end

app/views/ciudads/_form.html.erb
<%= form_for(@ciudad) do |f| %>
  <% if @ciudad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ciudad.errors.count, "error") %> prohibited this ciudad from being saved:</h2>

      <ul>
      <% @ciudad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :cod_ciudad %><br />
    <%= f.text_field :cod_ciudad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ciudads/edit.html.erb
<h1>Editing ciudad</h1>

<%= render 'form' %>

<%= link_to 'Show', @ciudad %> |
<%= link_to 'Back', ciudads_path %>

app/views/ciudads/index.html.erb
<h1>Lista de ciudades</h1>



<% @ciudads.each do |ciudad| %>
			<div class="post">
				<h2 class="title"><a href="#"><%= ciudad.nombre %></a></h2>
				<div style="clear: both;">&nbsp;</div>
				<div class="entry">
					<%= ciudad.cod_ciudad %>
					<%= link_to 'Show', ciudad %>
					<%= link_to 'Edit', edit_ciudad_path(ciudad) %>
					<%= link_to 'Destroy', ciudad, confirm: 'Are you sure?', method: :delete %>
					<%= link_to 'New Ciudad', new_ciudad_path %>
				</div>
			</div>
<% end %>
<br />

app/views/ciudads/new.html.erb
<h1>New ciudad</h1>

<%= render 'form' %>

<%= link_to 'Back', ciudads_path %>

app/views/ciudads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @ciudad.nombre %>
</p>

<p>
  <b>Cod ciudad:</b>
  <%= @ciudad.cod_ciudad %>
</p>


<%= link_to 'Edit', edit_ciudad_path(@ciudad) %> |
<%= link_to 'Back', ciudads_path %>