config/routes.rb
Listaslistas::Application.routes.draw do
  get 'admin' => 'admin#index'
controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end
  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :usuarios

  resources :homes

  resources :zonas

  resources :salas

  resources :reservas

  resources :imagen_eventos

  resources :imagen_discos

  resources :imagens

  resources :eventos

  resources :discotecas

  resources :ciudads

end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
end

app/models/discoteca.rb
class Discoteca < ActiveRecord::Base
validates :nombre, :cod_ciudad, :presence => true
end

app/models/evento.rb
class Evento < ActiveRecord::Base
validates :cod_disco, :nombre, :fecha ,:hora, :presence => true

validates :logo_web, :format => {
:with => %r{\.(gif|jpg|png)$}i,
:message => 'must be a URL for GIF, JPG or PNG image.'
}
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/imagen.rb
class Imagen < ActiveRecord::Base
end

app/models/imagen_disco.rb
class ImagenDisco < ActiveRecord::Base
end

app/models/imagen_evento.rb
class ImagenEvento < ActiveRecord::Base
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
end

app/models/sala.rb
class Sala < ActiveRecord::Base
end

app/models/usuario.rb
require 'digest/sha2'

class Usuario < ActiveRecord::Base
validates :nombre, :presence => true, :uniqueness => true

validates :password, :confirmation => true
attr_accessor :password_confirmation
attr_reader :password

validate :password_must_be_present

class << self
	def authenticate(nombre, password)
			if usuario = find_by_nombre(nombre)
				if usuario.hashed_password == encrypt_password(password, usuario.salt)
				usuario
			end
		end
	end
	def encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end
end

def password=(password)
@password = password
	if password.present?
		generate_salt
		self.hashed_password = self.class.encrypt_password(password, salt)
	end
end

after_destroy :ensure_an_admin_remains

def ensure_an_admin_remains
	if User.count.zero?
		raise "Can't delete last user"
	end
end

private
	def password_must_be_present
		errors.add(:password, "Missing password") unless hashed_password.present?
	end

	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s
	end
end

app/models/zona.rb
class Zona < ActiveRecord::Base
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservas }
    end
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
    @reserva = Reserva.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reserva }
    end
  end

  # GET /reservas/new
  # GET /reservas/new.json
  def new
    @reserva = Reserva.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reserva }
    end
  end

  # GET /reservas/1/edit
  def edit
    @reserva = Reserva.find(params[:id])
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(params[:reserva])

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: 'Reserva was successfully created.' }
        format.json { render json: @reserva, status: :created, location: @reserva }
      else
        format.html { render action: "new" }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservas/1
  # PUT /reservas/1.json
  def update
    @reserva = Reserva.find(params[:id])

    respond_to do |format|
      if @reserva.update_attributes(params[:reserva])
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva = Reserva.find(params[:id])
    @reserva.destroy

    respond_to do |format|
      format.html { redirect_to reservas_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/ciudads_helper.rb
module CiudadsHelper
end

app/helpers/discotecas_helper.rb
module DiscotecasHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/imagens_helper.rb
module ImagensHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/zonas_helper.rb
module ZonasHelper
end

app/views/reservas/_form.html.erb
<%= form_for(@reserva) do |f| %>
  <% if @reserva.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reserva.errors.count, "error") %> prohibited this reserva from being saved:</h2>

      <ul>
      <% @reserva.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cod_reserva %><br />
    <%= f.number_field :cod_reserva %>
  </div>
  <div class="field">
    <%= f.label :cod_evento %><br />
    <%= f.number_field :cod_evento %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :acompaniantes %><br />
    <%= f.number_field :acompaniantes %>
  </div>
  <div class="field">
    <%= f.label :contacto %><br />
    <%= f.text_field :contacto %>
  </div>
  <div class="field">
    <%= f.label :relaciones %><br />
    <%= f.number_field :relaciones %>
  </div>
  <div class="field">
    <%= f.label :origen %><br />
    <%= f.text_field :origen %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :hora %><br />
    <%= f.time_select :hora %>
  </div>
  <div class="field">
    <%= f.label :fijo %><br />
    <%= f.number_field :fijo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservas/edit.html.erb
<h1>Editing reserva</h1>

<%= render 'form' %>

<%= link_to 'Show', @reserva %> |
<%= link_to 'Back', reservas_path %>

app/views/reservas/index.html.erb
<h1>Listing reservas</h1>

<table>
  <tr>
    <th>Cod reserva</th>
    <th>Cod evento</th>
    <th>Nombre</th>
    <th>Acompaniantes</th>
    <th>Contacto</th>
    <th>Relaciones</th>
    <th>Origen</th>
    <th>Fecha</th>
    <th>Hora</th>
    <th>Fijo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reservas.each do |reserva| %>
  <tr>
    <td><%= reserva.cod_reserva %></td>
    <td><%= reserva.cod_evento %></td>
    <td><%= reserva.nombre %></td>
    <td><%= reserva.acompaniantes %></td>
    <td><%= reserva.contacto %></td>
    <td><%= reserva.relaciones %></td>
    <td><%= reserva.origen %></td>
    <td><%= reserva.fecha %></td>
    <td><%= reserva.hora %></td>
    <td><%= reserva.fijo %></td>
    <td><%= link_to 'Show', reserva %></td>
    <td><%= link_to 'Edit', edit_reserva_path(reserva) %></td>
    <td><%= link_to 'Destroy', reserva, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reserva', new_reserva_path %>

app/views/reservas/new.html.erb
<h1>New reserva</h1>

<%= render 'form' %>

<%= link_to 'Back', reservas_path %>

app/views/reservas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cod reserva:</b>
  <%= @reserva.cod_reserva %>
</p>

<p>
  <b>Cod evento:</b>
  <%= @reserva.cod_evento %>
</p>

<p>
  <b>Nombre:</b>
  <%= @reserva.nombre %>
</p>

<p>
  <b>Acompaniantes:</b>
  <%= @reserva.acompaniantes %>
</p>

<p>
  <b>Contacto:</b>
  <%= @reserva.contacto %>
</p>

<p>
  <b>Relaciones:</b>
  <%= @reserva.relaciones %>
</p>

<p>
  <b>Origen:</b>
  <%= @reserva.origen %>
</p>

<p>
  <b>Fecha:</b>
  <%= @reserva.fecha %>
</p>

<p>
  <b>Hora:</b>
  <%= @reserva.hora %>
</p>

<p>
  <b>Fijo:</b>
  <%= @reserva.fijo %>
</p>


<%= link_to 'Edit', edit_reserva_path(@reserva) %> |
<%= link_to 'Back', reservas_path %>