config/routes.rb
Listaslistas::Application.routes.draw do
  get 'admin' => 'admin#index'
controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end
  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :usuarios

  resources :homes

  resources :zonas

  resources :salas

  resources :reservas

  resources :imagen_eventos

  resources :imagen_discos

  resources :imagens

  resources :eventos

  resources :discotecas

  resources :ciudads

end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
end

app/models/discoteca.rb
class Discoteca < ActiveRecord::Base
validates :nombre, :cod_ciudad, :presence => true
end

app/models/evento.rb
class Evento < ActiveRecord::Base
validates :cod_disco, :nombre, :fecha ,:hora, :presence => true

validates :logo_web, :format => {
:with => %r{\.(gif|jpg|png)$}i,
:message => 'must be a URL for GIF, JPG or PNG image.'
}
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/imagen.rb
class Imagen < ActiveRecord::Base
end

app/models/imagen_disco.rb
class ImagenDisco < ActiveRecord::Base
end

app/models/imagen_evento.rb
class ImagenEvento < ActiveRecord::Base
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
end

app/models/sala.rb
class Sala < ActiveRecord::Base
end

app/models/usuario.rb
require 'digest/sha2'

class Usuario < ActiveRecord::Base
validates :nombre, :presence => true, :uniqueness => true

validates :password, :confirmation => true
attr_accessor :password_confirmation
attr_reader :password

validate :password_must_be_present

class << self
	def authenticate(nombre, password)
			if usuario = find_by_nombre(nombre)
				if usuario.hashed_password == encrypt_password(password, usuario.salt)
				usuario
			end
		end
	end
	def encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end
end

def password=(password)
@password = password
	if password.present?
		generate_salt
		self.hashed_password = self.class.encrypt_password(password, salt)
	end
end

after_destroy :ensure_an_admin_remains

def ensure_an_admin_remains
	if User.count.zero?
		raise "Can't delete last user"
	end
end

private
	def password_must_be_present
		errors.add(:password, "Missing password") unless hashed_password.present?
	end

	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s
	end
end

app/models/zona.rb
class Zona < ActiveRecord::Base
end

app/controllers/salas_controller.rb
class SalasController < ApplicationController
  # GET /salas
  # GET /salas.json
  def index
    @salas = Sala.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @salas }
    end
  end

  # GET /salas/1
  # GET /salas/1.json
  def show
    @sala = Sala.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sala }
    end
  end

  # GET /salas/new
  # GET /salas/new.json
  def new
    @sala = Sala.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sala }
    end
  end

  # GET /salas/1/edit
  def edit
    @sala = Sala.find(params[:id])
  end

  # POST /salas
  # POST /salas.json
  def create
    @sala = Sala.new(params[:sala])

    respond_to do |format|
      if @sala.save
        format.html { redirect_to @sala, notice: 'Sala was successfully created.' }
        format.json { render json: @sala, status: :created, location: @sala }
      else
        format.html { render action: "new" }
        format.json { render json: @sala.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /salas/1
  # PUT /salas/1.json
  def update
    @sala = Sala.find(params[:id])

    respond_to do |format|
      if @sala.update_attributes(params[:sala])
        format.html { redirect_to @sala, notice: 'Sala was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @sala.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salas/1
  # DELETE /salas/1.json
  def destroy
    @sala = Sala.find(params[:id])
    @sala.destroy

    respond_to do |format|
      format.html { redirect_to salas_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/ciudads_helper.rb
module CiudadsHelper
end

app/helpers/discotecas_helper.rb
module DiscotecasHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/imagens_helper.rb
module ImagensHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/zonas_helper.rb
module ZonasHelper
end

app/views/salas/_form.html.erb
<%= form_for(@sala) do |f| %>
  <% if @sala.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sala.errors.count, "error") %> prohibited this sala from being saved:</h2>

      <ul>
      <% @sala.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cod_sala %><br />
    <%= f.number_field :cod_sala %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :cod_ciudad %><br />
    <%= f.number_field :cod_ciudad %>
  </div>
  <div class="field">
    <%= f.label :cod_zona %><br />
    <%= f.number_field :cod_zona %>
  </div>
  <div class="field">
    <%= f.label :capacidad %><br />
    <%= f.number_field :capacidad %>
  </div>
  <div class="field">
    <%= f.label :localizacion %><br />
    <%= f.text_field :localizacion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salas/edit.html.erb
<h1>Editing sala</h1>

<%= render 'form' %>

<%= link_to 'Show', @sala %> |
<%= link_to 'Back', salas_path %>

app/views/salas/index.html.erb
<h1>Listing salas</h1>

<table>
  <tr>
    <th>Cod sala</th>
    <th>Nombre</th>
    <th>Cod ciudad</th>
    <th>Cod zona</th>
    <th>Capacidad</th>
    <th>Localizacion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @salas.each do |sala| %>
  <tr>
    <td><%= sala.cod_sala %></td>
    <td><%= sala.nombre %></td>
    <td><%= sala.cod_ciudad %></td>
    <td><%= sala.cod_zona %></td>
    <td><%= sala.capacidad %></td>
    <td><%= sala.localizacion %></td>
    <td><%= link_to 'Show', sala %></td>
    <td><%= link_to 'Edit', edit_sala_path(sala) %></td>
    <td><%= link_to 'Destroy', sala, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sala', new_sala_path %>

app/views/salas/new.html.erb
<h1>New sala</h1>

<%= render 'form' %>

<%= link_to 'Back', salas_path %>

app/views/salas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cod sala:</b>
  <%= @sala.cod_sala %>
</p>

<p>
  <b>Nombre:</b>
  <%= @sala.nombre %>
</p>

<p>
  <b>Cod ciudad:</b>
  <%= @sala.cod_ciudad %>
</p>

<p>
  <b>Cod zona:</b>
  <%= @sala.cod_zona %>
</p>

<p>
  <b>Capacidad:</b>
  <%= @sala.capacidad %>
</p>

<p>
  <b>Localizacion:</b>
  <%= @sala.localizacion %>
</p>


<%= link_to 'Edit', edit_sala_path(@sala) %> |
<%= link_to 'Back', salas_path %>