config/routes.rb
Listaslistas::Application.routes.draw do
  get 'admin' => 'admin#index'
controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end
  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :usuarios

  resources :homes

  resources :zonas

  resources :salas

  resources :reservas

  resources :imagen_eventos

  resources :imagen_discos

  resources :imagens

  resources :eventos

  resources :discotecas

  resources :ciudads

end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
end

app/models/discoteca.rb
class Discoteca < ActiveRecord::Base
validates :nombre, :cod_ciudad, :presence => true
end

app/models/evento.rb
class Evento < ActiveRecord::Base
validates :cod_disco, :nombre, :fecha ,:hora, :presence => true

validates :logo_web, :format => {
:with => %r{\.(gif|jpg|png)$}i,
:message => 'must be a URL for GIF, JPG or PNG image.'
}
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/imagen.rb
class Imagen < ActiveRecord::Base
end

app/models/imagen_disco.rb
class ImagenDisco < ActiveRecord::Base
end

app/models/imagen_evento.rb
class ImagenEvento < ActiveRecord::Base
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
end

app/models/sala.rb
class Sala < ActiveRecord::Base
end

app/models/usuario.rb
require 'digest/sha2'

class Usuario < ActiveRecord::Base
validates :nombre, :presence => true, :uniqueness => true

validates :password, :confirmation => true
attr_accessor :password_confirmation
attr_reader :password

validate :password_must_be_present

class << self
	def authenticate(nombre, password)
			if usuario = find_by_nombre(nombre)
				if usuario.hashed_password == encrypt_password(password, usuario.salt)
				usuario
			end
		end
	end
	def encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + "wibble" + salt)
	end
end

def password=(password)
@password = password
	if password.present?
		generate_salt
		self.hashed_password = self.class.encrypt_password(password, salt)
	end
end

after_destroy :ensure_an_admin_remains

def ensure_an_admin_remains
	if User.count.zero?
		raise "Can't delete last user"
	end
end

private
	def password_must_be_present
		errors.add(:password, "Missing password") unless hashed_password.present?
	end

	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s
	end
end

app/models/zona.rb
class Zona < ActiveRecord::Base
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/ciudads_helper.rb
module CiudadsHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/imagens_helper.rb
module ImagensHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/zonas_helper.rb
module ZonasHelper
end

app/views/admin/index.html.erb
<h1>Bienvenido</h1>
Son las <%= Time.now %>
Tenemos <%= pluralize(@total_eventos, "evento") %>.

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Atmosphere 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20110923

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Listaslistas</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />

<!-- Esto es una guarrada, pero evita el problema de que no cargue el css dependiendo de la ruta. Por mejorar-->
<link href="stylesheets/style.css" rel="stylesheet" type="text/css" media="screen" />
<link href="../stylesheets/style.css" rel="stylesheet" type="text/css" media="screen" />
<link href="../../stylesheets/style.css" rel="stylesheet" type="text/css" media="screen" />

<!-- Scripts para subir imagenes-->
<script type="text/javascript" src="javascript/jquery-pack.js"></script>
<script type="text/javascript" src="javascript/jquery.imgareaselect.min.js"></script>

</head>
<body>
<div id="wrapper">
	<div id="header" class="container">
		<div id="logo">
			<h1><a href="#">Listaslistas </a></h1>
			<p>Diseñado por <a href="http://www.freecsstemplates.org/">Ayalavalley</a></p>
		</div>
		<div id="menu">
			<ul>
				<li class="current_page_item"><a href="homes">Home</a></li>
				<li><a href="discotecas">Discotecas</a></li>
				<li><a href="eventos">Eventos</a></li>
				<li><a href="login">Login</a></li>
			</ul>
		</div>
	</div>
	<!-- end #header -->
	<div id="page">
		<div id="content">
			<div class="post">
				<h2 class="title"><a href="#">Alistate! </a></h2>
				<p class="meta"><span class="date">August 28, 2011</span><span class="posted">Posted by <a href="#">Ayalavalley</a></span></p>
				<div style="clear: both;">&nbsp;</div>
				<div class="entry">
					<%= yield %>
				</div>
			</div>

			<div style="clear: both;">&nbsp;</div>
		</div>
		<!-- end #content -->
		<div id="sidebar">
			<ul>
				<li>
					<div id="search" >
						<form method="get" action="#">
							<div>
								<input type="text" name="s" id="search-text" value="" />
								<input type="submit" id="search-submit" value="GO" />
							</div>
						</form>
					</div>
					<div style="clear: both;">&nbsp;</div>
				</li>
				<li>
					<h2>¿Que es listaslistas?</h2>
					<p>¿gestionas un pub, club, local o discoteca?<br>¿estas aburrido de gestionar tus listas de puerta de forma manual?<br>¿quieres dejar de hacer "listas tontas" y empezar a hacer "listas listas"?<br>¡escribenos! te ayudaremos a hacer listas como churros<br>info@listaslistas.com</p>
				<% if session[:usuario_id] %>
				  <br />
				  <%= link_to 'Discotecas', discotecas_path %> <br />
				  <%= link_to 'Eventos', eventos_path %><br />
				  <%= link_to 'Usuarios', usuarios_path %><br />
				  <br />
				  <%= button_to 'Logout', logout_path, :method => :delete %>
				<% end %>
				</li>
			</ul>
		</div>
		<!-- end #sidebar -->
		<div style="clear: both;">&nbsp;</div>
	</div>
	<!-- end #page -->
</div>
<div id="footer-content">
	<div id="footer-bg" class="container">
		<div id="column1">
			<h2>Bienvenido!</h2>
			<p>Listaslistas nace con el objetivo de agilizar y revolucionar la gestión de clientes para discotecas. Con listaslistas podras crear los eventos que se publican en la aplicación para móviles Muchanoche. En Muchanoche millones de personas veran tu evento y se podran meter en lista sin intermediarios! Entra ya en la noche de Muchanoche y listaslistas!</p>
		</div>
		<div id="column2">
			<h2>Etiam rhoncus volutpat</h2>
			<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus consectetuer. Donec ipsum. Proin imperdiet est. Phasellus dapibus semper urna.</p>
		</div>
		<div id="column3">
			<h2>Recommended Links</h2>
			<ul>
				<li><a href="#">Consectetuer adipiscing elit</a></li>
				<li><a href="#">Metus aliquam pellentesque</a></li>
				<li><a href="#">Suspendisse iaculis mauris</a></li>
				<li><a href="#">Urnanet non molestie semper</a></li>
				<li><a href="#">Proin gravida orci porttitor</a></li>
			</ul>
		</div>
	</div>
</div>
<div id="footer">
	<p>Copyright (c) 2011 Sitename.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
</div>
<!-- end #footer -->
</body>
</html>